[package]
name = "heap_size_derive"
version = "0.1.0"
authors = ["shota.f <shota.fk8@gmail.com>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"
